[project]
name = "generate-quarto-invoices"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "python-dateutil>=2.9.0.post0",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "isort>=6.0.1",
]
